var mainModule=angular.module('mainModule',['routerModule','servicesModel','multimeterModule','obdscanModule','dashboardModule','xcj.Service','xcj.validate'])

mainModule.controller('mainCtrl',['$scope','$compile','$rootScope','$state','serviceData','$timeout','multimeterService','obdscanService','xcjService','validateService','pageService',function($scope,$compile,$rootScope,$state,serviceData,$timeout,multimeterService,obdscanService,xcjService,validateService,pageService){
	//获取控制界面的services值（优化部分）
	$scope.pageServiceMdata=pageService.Mdata;
	
//	//主界面的ng-include的src初始值
//	$scope.systemCircuitSrc='template/circuit.html';
//	$scope.systemPrincipleSrc='template/principle.html';
	//右侧工具栏中图片名字
//	$scope.aToolBlock=['right-diagnostic','right-multimeter','right-vacuumPump','right-airGun','right-wireCutter','right-pinchClamp','right-cylinderPressure','right-fuelPressure']
	//车上位置使用的图片
//	$scope.placeImgSrc:['images/alert_position_1.png','images/alert_position_2.png','images/alert_position_3.png','images/alert_position_4.png','images/alert_position_5.png','images/alert_position_6.png','images/alert_position_7.png','images/alert_position_8.png'],
	//左侧导航中的字符串
//	$scope.aNaviBlock:['结构原理','诊断测量','故障排除','知识拓展','技能测试']
	
	//显示隐藏控制
	$scope.showOrHide=$scope.pageServiceMdata.showOrHide;
	//内容改变
	$scope.chargeData=$scope.pageServiceMdata.chargeData;
	//车上位置图片的链接
//	$scope.placeImgSrc=$scope.chargeData.placeImgSrc;
	//左侧导航中的字符串
//	$scope.aNaviBlock=$scope.chargeData.aNaviBlock;
	
	//弹出框中主题页面的ng-include的src初始值
	$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
	//用于切换左侧导航中的信息的下标
	var naviIndex=0;
	//左侧导航中的字符串(默认为空)，用来增加样式的
	$scope.sNaviText='';
	//把service中的值给serviceDataPNavi(存储的是某一块导航所对应的数据，并不是全部数据，这里使用这种方式赋值是为了防止json中数据顺序乱了，还能拿到正确数据)
	$scope.serviceDataPNavi=serviceData.PNavi[getServiceIndex(naviIndex)];
	//弹出框导航块中的字符串(默认系统概述)
	$scope.sAlertNaviText=$scope.serviceDataPNavi.aAlertNaviBlock[0];
	//改变弹出框中的模板导航块的内容和图片
	$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[0];
//	$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
	//拿到失效模式中的数据，全部数据(初始系统原理下的第一个失效模式)
	$scope.serviceDataPFail=serviceData.PFail['failure'][0];
	
	
	//是否显示下面的进入故障和故障清除按钮
//	$scope.bShowFooter=true;
	//题目内容的对象，每道题是一个对象，对象中包含了这道题的数据
//	$scope.jQuestion={}
	//如果回答正确则显示相应的提示;
//	$scope.answerCurrect=false;
//	$scope.answerWrong=false;
	//是否允许进入检测
//	$scope.isGoCheck=false;
	//是否允许清除故障
//	$scope.isGoClear=false;
	//元件检测和结构原理下的系统组成单独页面的显示(使用不同模板)
//	$scope.alertBodyChoice=false;
	
	//页面中点击图出现弹出框中元件检测和失效模式置灰变量(false置灰，true不置灰)
//	$scope.alertComponent=true;
//	$scope.alertPlace=true;
//	$scope.alertFail=true;
	//页面中点击图出现弹出框中元件检测和失效模式是否是触发状态(false不触发，true触发)
//	$scope.principleAlertComponentActive=false;
//	$scope.principleAlertPlaceActive=false;
//	$scope.principleAlertFailActive=false;
	//页面中点击图出现弹出框中元件检测和失效模式是否是触发状态(false不触发，true触发)
//	$scope.circuitAlertComponentActive=false;
//	$scope.circuitAlertPlaceActive=false;
//	$scope.circuitAlertFailActive=false;
	
	//=======================================================================================================
	//取service中的数据（得到索引，五个导航中的第几个数据）
	function getServiceIndex(a){
		var index='';
		angular.forEach(serviceData.PNavi,function(item,key){
			if($scope.chargeData.aNaviBlock[a]==item.id){
				index=key;
				return;
			}
		})
		return index
	};
	
	//改变顶部系统导航的ng-include的src(val为0跳到系统电路，1跳到系统原理)============================================
	$scope.chargeSrc=function(val){
		if(val){
			//切换到系统原理界面
			$scope.showOrHide.circuitOrPrinciple=false;
			//导航条样式切换
			$(".header button").removeClass("header-navi-bg");
			$(".header button:first").addClass("header-navi-bg");
			sysStay=2;
			//收掉万用表
			multimeterService.Mdata.multimeterblackRecover();
			multimeterService.Mdata.multimeterredRecover();
		}else{
			//切换到系统电路页面
			$scope.showOrHide.circuitOrPrinciple=true;
			//导航条样式切换
			$(".header button").removeClass("header-navi-bg");
			$(".header button:last").addClass("header-navi-bg");
			sysStay=1;
			//刷新万用表热区
			$timeout(function () {multimeterService.Mdata.freshHontspot();}, 100);
			//收掉万用表
			multimeterService.Mdata.multimeterblackRecover();
			multimeterService.Mdata.multimeterredRecover();
		}
	}
	//右侧工具的使用============================================================================================

	//左侧导航的切换============================================================================================
	$scope.chargeLeftNavi=function(navi){
		//显示弹出框
		$scope.showOrHide.alertContain=true;
		//左侧导航加上触发样式
		$scope.sNaviText=navi;
		//获取点击的是第几个导航块
		naviIndex=getArrIndex(navi,$scope.chargeData.aNaviBlock);
		//根据是第几个导航块切换数据(存储的是某一块的数据，并不是全部数据)
		$scope.serviceDataPNavi=serviceData.PNavi[getServiceIndex(naviIndex)];
		//加上弹出框导航条中的默认触发（第一个）样式
		$scope.sAlertNaviText=$scope.serviceDataPNavi.aAlertNaviBlock[0];
		//每个导航块的单独事件-----------------------------------------------------------------------------------------------
		if($scope.serviceDataPNavi.id==$scope.chargeData.aNaviBlock[0]){
			//设置选择哪个导航块状态码
			leftNaviStay=1;
			//禁止元件检测按钮和失效模式
			$scope.showOrHide.alertComponent=false;
//			$scope.showOrHide.alertFail=false;
			//弹出框开始的主体跳转到这个页面
			$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
			//改变弹出框中的模板导航块
			$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[0];
			//隐藏拓展1中的图片
//			$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
			//隐藏清除故障进入故障按钮
			$scope.showOrHide.bShowFooter=true;
			//第一个页面先默认吧主体跳转到系统原理页面
			$scope.chargeSrc(1);
			//如果点击了提交，初始化技能测试
			if(bSubmit){
				InitQuestion();
			}
			//记录进度
			recordHistory('A001');
		}
		if($scope.serviceDataPNavi.id==$scope.chargeData.aNaviBlock[1]){
			//设置选择哪个导航块状态码
			leftNaviStay=2;
			//解放元件检测按钮和失效模式
			$scope.showOrHide.alertComponent=true;
			$scope.showOrHide.alertFail=true;
			//显示 元件测量 的那部分页面
			$scope.showOrHide.alertLinkComponentsInfo=false;
			$scope.showOrHide.alertLinkPrincipleInfo=false;
			$scope.showOrHide.alertLinkMeasuringInfo=true;
			//弹出框开始的主体跳转到这个页面
			$scope.alertBodySrc=toAlertBodySrc('alert_body_measure_link.html');
			//改变弹出框中的模板导航块
			$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[0];
			//隐藏拓展1中的图片
//			$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
			//隐藏清除故障进入故障按钮
			$scope.showOrHide.bShowFooter=true;
			//如果点击了提交，初始化技能测试
			if(bSubmit){
				InitQuestion();
			}
			//记录进度
			recordHistory('A002');
		}
		if($scope.serviceDataPNavi.id==$scope.chargeData.aNaviBlock[2]){
			//设置选择哪个导航块状态码
			leftNaviStay=3;
			//解放元件检测按钮和失效模式
			$scope.showOrHide.alertComponent=true;
			$scope.showOrHide.alertFail=true;
			//弹出框开始的主体跳转到这个页面
			$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
			//改变弹出框中的模板导航块
			$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[0];
			//隐藏拓展1中的图片
//			$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
			//显示清除故障进入故障按钮
			$scope.showOrHide.bShowFooter=false;
			//如果点击了提交，初始化技能测试
			if(bSubmit){
				InitQuestion();
			}
			//判断进入故障，清除故障两个按钮的显示隐藏情况
			GoCheckStay(1);
			//记录进度
			recordHistory('A003');
		}
		if($scope.serviceDataPNavi.id==$scope.chargeData.aNaviBlock[3]){
			//设置选择哪个导航块状态码
			leftNaviStay=4;
			//解放元件检测按钮和失效模式
			$scope.showOrHide.alertComponent=true;
			$scope.showOrHide.alertFail=true;
			//弹出框开始的主体跳转到这个页面
			$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html')
			//改变弹出框中的模板导航块
			$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[0];
			//显示拓展1中的图片
			$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
			//隐藏清除故障进入故障按钮
			$scope.showOrHide.bShowFooter=true;
			//如果点击了提交，初始化技能测试
			if(bSubmit){
				InitQuestion();
			}
			//记录进度
			recordHistory('A004');
		}
		if($scope.serviceDataPNavi.id==$scope.chargeData.aNaviBlock[4]){
			//设置选择哪个导航块状态码
			leftNaviStay=5;
			//解放元件检测按钮和失效模式
			$scope.showOrHide.alertComponent=true;
			$scope.showOrHide.alertFail=true;
			//弹出框开始的主体跳转到这个页面
			$scope.alertBodySrc=toAlertBodySrc('alert_body_choice.html')
			//隐藏拓展1中的图片
			$scope.aAlertNaviImg=$scope.serviceDataPNavi.aImgSrc;
			//隐藏清除故障进入故障按钮
			$scope.showOrHide.bShowFooter=true;
			//给题目内容赋值,默认先赋值第一道题的数据，但这里用一个变量来记录
			$scope.chargeData.jQuestion=$scope.serviceDataPNavi.question[questionNo];
			//记录进度
			recordHistory('A005');
		}
		//加上拖拽事件
		dragDiv();
	}
	
	//弹出框中的导航块上的事件-----------------------------------------------------------------------------------
	$scope.chargeAlertNavi=function(index){
		//取navi的值
		var navi=$scope.serviceDataPNavi.aAlertNaviBlock[index];
		//改变弹出框导航中的样式
		$scope.sAlertNaviText=navi;
		//判断点击的是 左侧导航哪一块的第几个=======================================================================================
		//把这个导航中service的数据加给主体
		$scope.aAlertNaviText=$scope.serviceDataPNavi.aAlertText[index];
		if(leftNaviStay==1){
			if(index==0){//系统概述--------------

				//跳转到原理页面
				$scope.chargeSrc(1);
				//弹出框开始的主体跳转到这个页面
				$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
			}
			if(index==1){//系统原理--------------
				//记录进度
				recordHistory('A021');
				//跳转到原理页面
				$scope.chargeSrc(1);
				//显示 系统原理 的那部分页面
				$scope.showOrHide.alertLinkComponentsInfo=false;
				$scope.showOrHide.alertLinkPrincipleInfo=true;
				$scope.showOrHide.alertLinkMeasuringInfo=false;
				//弹出框开始的主体跳转到这个页面
				$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
			}
			if(index==2){//系统组成--------------
				//记录进度
				recordHistory('A022');
				//跳转到原理页面
				$scope.chargeSrc(1);
				//显示 系统组成 的那部分页面
				$scope.showOrHide.alertLinkComponentsInfo=true;
				$scope.showOrHide.alertLinkPrincipleInfo=false;
				$scope.showOrHide.alertLinkMeasuringInfo=false;
				//弹出框开始的主体跳转到这个页面
				$scope.alertBodySrc=toAlertBodySrc('alert_body_measure_link.html');	
			}
			if(index==3){//系统电路--------------
				//记录进度
				recordHistory('A023');
				//跳转到电路页面
				$scope.chargeSrc(0);
				//显示 系统电路 的那部分页面
				$scope.showOrHide.alertLinkComponentsInfo=false;
				$scope.showOrHide.alertLinkPrincipleInfo=true;
				$scope.showOrHide.alertLinkMeasuringInfo=false;
				//弹出框开始的主体跳转到这个页面
				$scope.alertBodySrc=toAlertBodySrc('alert_body_measure_link.html');
			}
		}
		if(leftNaviStay==2){
			if(index==0){//元件测量--------------
				//显示 元件测量 的那部分页面
				$scope.showOrHide.alertLinkComponentsInfo=false;
				$scope.showOrHide.alertLinkPrincipleInfo=false;
				$scope.showOrHide.alertLinkMeasuringInfo=true;
				//元件测量 要跳转模板
				$scope.alertBodySrc=toAlertBodySrc('alert_body_measure_link.html');
//				//背景换成系统原理
//				$scope.chargeSrc(1);
			}
			if(index==1){//电路测量--------------
				//记录进度
				recordHistory('A024');
				//隐藏系统组成的那部分页面
//				$scope.alertBodyChoice=true;
				//电路测量 要跳转模板
				$scope.alertBodySrc=toAlertBodySrc('alert_body_text.html');
//				//背景换成系统电路
//				$scope.chargeSrc(0);
			}
		}
		if(leftNaviStay==3){
			//判断进入故障按钮的显示隐藏
			GoCheckStay(index+1);
			if(index==0){//故障1--------------
				
			}
			if(index==1){//故障2--------------
				//记录进度
				recordHistory('A025');
			}
		}
		if(leftNaviStay==4){//知识拓展--------------
			
		}
		if(leftNaviStay==5){//技能测试--------------
		
		}
	}
	//元件检测和系统组成中a标签的跳转方法----------------------------------------
	$scope.goInclude=function(id){
		//弹出框开始的主体跳转到这个页面
		$scope.alertBodySrc=toAlertBodySrc('alert_information.html');
		var aNo=id.split("-");
		
		//系统组成中的a链接
		//系统原理-------------------------------------------------
		if(aNo[0]=='sysPrinciple'){
			//得到一个对象，包含多个数据信息
			$scope.jInfo=$scope.aAlertNaviText[aNo[1]];
			//记录进度
			recordHistory("D0"+(40+parseInt(aNo[1])));
		}
		//系统组成-------------------------------------------------
		if(aNo[0]=='sysComposition'){
			//得到一个对象，包含多个数据信息
			$scope.jInfo=$scope.aAlertNaviText[aNo[1]];
			//记录进度
			recordHistory("D0"+(46+parseInt(aNo[1])));
		}
		//诊断测量-------------------------------------------------
		if(aNo[0]=='diagnosisMeasurements'){
			//得到一个对象，包含多个数据信息
			$scope.jInfo=$scope.aAlertNaviText[aNo[1]];
			//记录进度
			recordHistory("D0"+(53+parseInt(aNo[1])));
		}
	}
	//信息页面返回元件检测和系统组成界面
	$scope.goBackPre=function(){
		//弹出框开始的主体跳转到这个页面
		$scope.alertBodySrc=toAlertBodySrc('alert_body_measure_link.html');
	}
	//判断进入故障，清除故障两个按钮的显示隐藏情况-----------------------------------
	function GoCheckStay(val){
		if(val==1){
			if(goCheckStay==1){
				//解放清除故障
				$scope.showOrHide.isGoClear=true;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=false;
			}else if(goCheckStay==0){
				//禁止清除故障
				$scope.showOrHide.isGoClear=false;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=true;
			}else{
				//禁止清除故障(多个故障是使用这个)
				$scope.showOrHide.isGoClear=false;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=false;
			}
		}else if(val==2){
			if(goCheckStay==2){
				//解放清除故障
				$scope.showOrHide.isGoClear=true;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=false;
			}else if(goCheckStay==0){
				//禁止清除故障
				$scope.showOrHide.isGoClear=false;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=true;
			}else{
				//禁止清除故障(多个故障是使用这个)
				$scope.showOrHide.isGoClear=false;
				//禁止进入故障
				$scope.showOrHide.isGoCheck=false;
			}
		}else{};
		
	}
	//进入故障-------------------------------------------------------------------------------------
	$scope.goMalfunctionCheck=function(){
		//进入故障1
		if($scope.sAlertNaviText==$scope.serviceDataPNavi.aAlertNaviBlock[0]){
			//模型通讯
			pageService.Mint.In1ERV_High_Gear_x_Fault='0';
			//进入故障状态码设定
			goCheckStay=1;
			//判断进入故障和清除故障的显示隐藏
			GoCheckStay(1);
			//显示故障动画
			$scope.goMalfunctionAnimate();
			//修改工作状态标示码
			$scope.showOrHide.workState=false;
			$(".worker-state").text("故障工作状态下");
			//记录进度
			recordHistory("B026");
		}
		//进入故障2
		if($scope.sAlertNaviText==$scope.serviceDataPNavi.aAlertNaviBlock[1]){
			//模型通讯
			pageService.Mint.In1Fid_Fail_APP_Four_x='0';
			//进入故障状态码设定
			goCheckStay=2;
			//判断进入故障和清除故障的显示隐藏
			GoCheckStay(2);
			//显示故障动画
			$scope.goMalfunctionAnimate();
			//修改工作状态标示码
			$scope.showOrHide.workState=false;
			$(".worker-state").text("故障工作状态下");
			//记录进度
			recordHistory("B027");
		}
	}
	//清除故障
	$scope.ClearMalfunction=function(){
		//清除故障1
		if($scope.sAlertNaviText==$scope.serviceDataPNavi.aAlertNaviBlock[0]){
			//模型通讯
			pageService.Mint.In1ERV_High_Gear_x_Fault='1';
			//进入故障状态码设定
			goCheckStay=0;
			//判断进入故障和清除故障的显示隐藏
			GoCheckStay(1);
			//显示故障动画
			$scope.clearMalfunctionAnimate();
			//修改工作状态标示码
			$scope.showOrHide.workState=true;
			$(".worker-state").text("正常工作状态下");
			//记录进度
//			recordHistory("B028");
		}
		//清除故障2
		if($scope.sAlertNaviText==$scope.serviceDataPNavi.aAlertNaviBlock[1]){
			//模型通讯
			pageService.Mint.In1Fid_Fail_APP_Four_x='1';
			//进入故障状态码设定
			goCheckStay=0;
			//判断进入故障和清除故障的显示隐藏
			GoCheckStay(2);
			//显示故障动画
			$scope.clearMalfunctionAnimate();
			//修改工作状态标示码
			$scope.showOrHide.workState=true;
			$(".worker-state").text("正常工作状态下");
			//记录进度
//			recordHistory("B028");
		}
	}
	//上一题下一题模板========================================================================================
	$scope.preQuestion=function(){
		questionNo--;
		if(questionNo<=0){
			questionNo=0;
		}
		//判断下一步上一步按钮的置灰与否
		isShowPreONext();
		//跳到上一题
		goQuestion();
	}
	$scope.nextQuestion=function(){
		questionNo++;
		if(questionNo>=9){
			questionNo=9;
		}
		//判断下一步上一步按钮的置灰与否
		isShowPreONext();
		//跳到下一题
		goQuestion();
	}
	//提交方法
	$scope.questionSubmit=function(){
		//记录进度
		recordHistory("A020");
		//是否提交了答案的判别码
		bSubmit=true;
		//判断当前这道题的正确与否，并相应的显示判断
		var answer="no"+questionNo;
		if($scope.chargeData.jQuestion.trueAnswer==jAnswer[answer]){
			//如果答案正确，那就显示正确，
			$scope.showOrHide.answerWrong=false;
			$scope.showOrHide.answerCurrect=true;
		}else{
			//不正确就显示正确答案
			$scope.showOrHide.answerCurrect=false;
			$scope.showOrHide.answerWrong=true;
		}
		//置灰提交按钮
		$(".question-submit").addClass("disable").removeClass("cursor-pointer");
	}
	
	//题组跳转
	function goQuestion(){
		//把questionNo拼接成jAnswer的
		var answer="no"+questionNo;
		//赋一套题的数据
		$scope.chargeData.jQuestion=$scope.serviceDataPNavi.question[questionNo];
		//检测答案情况，判断选项选中的样式
		 answerCheck();
		 //提交后判断这到题是否答对了
		if(bSubmit){
			if($scope.chargeData.jQuestion.trueAnswer==jAnswer[answer]){
			 	//如果答案正确，那就显示正确，
				$scope.showOrHide.answerWrong=false;
				$scope.showOrHide.answerCurrect=true;
			}else{
			 	//不正确就显示正确答案
				$scope.showOrHide.answerCurrect=false;
				$scope.showOrHide.answerWrong=true;
			}
		}
	}
	//初始化技能测试
	function InitQuestion(){
		//初始化提交的答案
		for(j in jAnswer){
			jAnswer[j]='';
		};
		//初始化题号
		questionNo=0;
		//去掉下面的错误提示
		$scope.showOrHide.answerCurrect=false;
		$scope.showOrHide.answerWrong=false;
		//检测答案情况，判断样式
		 answerCheck();
		 bSubmit=false;
		//高亮提交按钮
		$(".question-submit").addClass("cursor-pointer").removeClass("disable");
	}
	
	
	//弹出框关闭按钮的额外事件(把左侧默认选中的导航块去除触发状态)
	$scope.closeDivAngu=function (){
		//关闭弹出框
		$scope.showOrHide.alertContain=false;
		//去除左侧导航块触发状态样式
		$scope.sNaviText='';
		//初始化导航块状态码
		leftNaviStay=0;
		//解放元件检测按钮
		$scope.showOrHide.alertComponent=true;
		$scope.showOrHide.alertFail=true;
		//如果点击了提交，初始化技能测试
		if(bSubmit){
			InitQuestion();
			isShowPreONext();
		}
	}
		
	//打开页面中点火线圈，火花塞，凸轮轴传感器，爆震传感器，曲轴传感器等弹出框===============================================================================
	$scope.bodyAlert=function(id){
//		//记录进度
//		recordHistory("原理图或电路图弹出框"+id);
		//如果左侧导航处在结构原理下，置灰两个按钮
		if(leftNaviStay==1){
			$scope.showOrHide.alertComponent=false;
//			$scope.showOrHide.alertFail=false;
		}else{
			$scope.showOrHide.alertComponent=true;
//			$scope.showOrHide.alertFail=true;
		}
		//系统电路 页面下
		if(sysStay==1){
			//专门写来应对多个热点功能相同的事件----------------------------
			if(sysCircuitAlert==id){
				return;
			};
			//先关闭所有弹出框极其部件-----------------------------------
			$scope.sysAlertClose();
			//直接设置该弹出状态码
			sysCircuitAlert=id;
			//根据点击的东西来确认sysCircuitAlert状态吗来改变显隐
			if(sysCircuitAlert==1){
				//弹出 主开关
				$scope.showOrHide.circuitAlertOne=true;
				//记录进度
				recordHistory("C028");
			};
			if(sysCircuitAlert==2){
				//弹出 右前开关
				$scope.showOrHide.circuitAlertTwo=true;
				//记录进度
				recordHistory("C029");
			};
			if(sysCircuitAlert==3){
				//弹出 左后开关
				$scope.showOrHide.circuitAlertThree=true;
				//记录进度
				recordHistory("C030");
			};
			if(sysCircuitAlert==4){
				//弹出 主电机
				$scope.showOrHide.circuitAlertFour=true;
				//记录进度
				recordHistory("C031");
			};
			if(sysCircuitAlert==5){
				//弹出 右前电机
				$scope.showOrHide.circuitAlertFive=true;
				//记录进度
				recordHistory("C032");
			};
			if(sysCircuitAlert==6){
				//弹出 左后电机
				$scope.showOrHide.circuitAlertSix=true;
				//记录进度
				recordHistory("C033");
			};
		}
		//系统原理 页面下
		if(sysStay==2){
			if(sysPrincipleAlert==id){
				return;
			}
			//先关闭所有弹出框极其部件
			$scope.sysAlertClose();
			//直接设置该弹出状态码
			sysPrincipleAlert=id;
			//根据点击的东西来确认sysPrincipleAlert状态吗来改变显隐
			if(sysPrincipleAlert==1){
				//弹出 高压油泵
				$scope.showOrHide.principleAlertOne=true;
				//记录进度
				recordHistory("C028");
			};
			if(sysPrincipleAlert==2){
				//弹出 进油计量比例阀故障
				$scope.showOrHide.principleAlertTwo=true;
				//记录进度
				recordHistory("C029");
			};
			if(sysPrincipleAlert==3){
				//弹出 加速踏板位置传感器
				$scope.showOrHide.principleAlertThree=true;
				//记录进度
				recordHistory("C030");
			};
			if(sysPrincipleAlert==4){
				//弹出 燃油共轨
				$scope.showOrHide.principleAlertFour=true;
				//记录进度
				recordHistory("C031");
			};
			if(sysPrincipleAlert==5){
				//弹出 共轨压力传感器
				$scope.showOrHide.principleAlertFive=true;
				//记录进度
				recordHistory("C032");
			};
			if(sysPrincipleAlert==6){
				//弹出 喷油器
				$scope.showOrHide.principleAlertSix=true;
				//记录进度
				recordHistory("C033");
			};
		}
	}
	//系统中弹出框关闭按钮额外事件
	$scope.sysAlertClose=function(){
		//关闭所有元件测量
		$scope.closeComponent();
		//关闭车上位置
		$scope.closePlace();
		//关闭失效模式
		$scope.closeFail();
		//同时关闭车上位置弹出图片框
		if(sysStay==1){
			//关闭所有弹出框
			$scope.showOrHide.circuitAlertOne=false;
			$scope.showOrHide.circuitAlertTwo=false;
			$scope.showOrHide.circuitAlertThree=false;
			$scope.showOrHide.circuitAlertFour=false;
			$scope.showOrHide.circuitAlertFive=false;
			$scope.showOrHide.circuitAlertSix=false;
			//标识码置为0
			sysCircuitAlert=0;
		}
		if(sysStay==2){
			//关闭所有弹出框
			$scope.showOrHide.principleAlertOne=false;
			$scope.showOrHide.principleAlertTwo=false;
			$scope.showOrHide.principleAlertThree=false;
			$scope.showOrHide.principleAlertFour=false;
			$scope.showOrHide.principleAlertFive=false;
			$scope.showOrHide.principleAlertSix=false;
			$scope.showOrHide.principleAlerSeven=false;
			$scope.showOrHide.principleAlertEight=false;
			
			//标识码置为0
			sysPrincipleAlert=0;
		}
	}
	//元件检测方法--------------------------------------------------------------------------
		//弹出元件检测界面并加上相应事件
	//显示相应的元件检测界面
	$scope.sysAlertComponent=function(id){
		//记录进度
		recordHistory(id);
		//一个元件每次只允许打开三个弹出框中的一个(所以先关闭所有打开的弹出框)
		$scope.closeComponent();
		$scope.closePlace();
		$scope.closeFail();
		if(sysStay==1){
			//增加触发状态
			$scope.showOrHide.circuitAlertComponentActive=true;
			//显示元件检测界面
			$scope.showOrHide.circuitComponent=true;
			//显示具体那一个 
			if(sysCircuitAlert==1){
				//显示点火线圈元件
				$scope.showOrHide.circuitAlertOneComponent=true;
			}
			if(sysCircuitAlert==2){
				//显示凸轮轴元件
				$scope.showOrHide.circuitAlertTwoComponent=true;
			}
			if(sysCircuitAlert==3){
				//显示爆震传感器元件
				$scope.showOrHide.circuitAlertThreeComponent=true;
			}
			if(sysCircuitAlert==4){
				//显示曲轴元件
//				$scope.showOrHide.circuitAlertFourComponent=true;
			}
			if(sysCircuitAlert==5){
				//显示曲轴元件
				$scope.showOrHide.circuitAlertFiveComponent=true;
			}
			if(sysCircuitAlert==6){
				//显示曲轴元件
				$scope.showOrHide.circuitAlertSixComponent=true;
			}
			//打开了元件检测或车上位置或失效模式状态码
			circuitAlertStay=1;
			//打开了同时收回表笔
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//改变万用表热区的显示隐藏状态
			showAHot();
		}
		if(sysStay==2){
			//增加触发状态
			$scope.showOrHide.principleAlertComponentActive=true;
			//显示元件检测界面
			$scope.showOrHide.principleComponent=true;
			//显示具体那一个 
			if(sysPrincipleAlert==1){
				//显示点火线圈元件
				$scope.showOrHide.principleAlertOneComponent=true;
//				//拔开点火线圈，当故障处理
//				pageService.Mint.In1Sen_OP_Conn_x_Install='0';
				//（on状态动画）===================================================
//				if(stalls==4){
//					//初始化原理动画动画
//					principleAnimateInitialize();
//					//执行系统原理动画(给了执行口令，开始执行动画才能执行,这里是为了预防点不着火的交互)
//					isRunAnimate=1;
//					//系统原理线路箭头的动画
//					principleArrowFlowRepeat(parseInt(principleAnimateTime)*2);
//					
//					//初始化电路图中点火线圈发射信号------------------------------------------
//					clearInterval(timerIgnationLineFlash);
//					isFlashLineOpen=1;
//					$(".fixed-late-show-flash-line span").stop().css("background","#000000");
//				}
				
				//======================================================================
			}
			if(sysPrincipleAlert==2){
				//显示火花塞元件
				$scope.showOrHide.principleAlertTwoComponent=true;
			}
			if(sysPrincipleAlert==3){
				//显示凸轮轴元件
				$scope.showOrHide.principleAlertThreeComponent=true;
			}
			if(sysPrincipleAlert==4){
				//显示爆震传感器元件
				$scope.showOrHide.principleAlertFourComponent=true;
			}
			if(sysPrincipleAlert==5){
				//显示曲轴元件
				$scope.showOrHide.principleAlertFiveComponent=true;
			}
			if(sysPrincipleAlert==6){
				//显示曲轴元件
				$scope.showOrHide.principleAlertSixComponent=true;
			}
		}
	}
	//元件检查关闭方法-----------------
	$scope.closeComponent=function(){
		if(sysStay==1){
			//去除按钮触发状态
			$scope.showOrHide.circuitAlertComponentActive=false;
			//隐藏元件检测界面
			$scope.showOrHide.circuitComponent=false;
			//隐藏所有的界面
			$scope.showOrHide.circuitAlertOneComponent=false;
			$scope.showOrHide.circuitAlertTwoComponent=false;
			$scope.showOrHide.circuitAlertThreeComponent=false;
			$scope.showOrHide.circuitAlertFourComponent=false;
			$scope.showOrHide.circuitAlertFiveComponent=false;
			$scope.showOrHide.circuitAlertSixComponent=false;
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//隐藏了元件检测或车上位置或失效模式状态码
			circuitAlertStay=0;
			//改变万用表热区的显示隐藏状态
			showAHot();
		}
		if(sysStay==2){
			//拔开点火线圈，当故障处理
			pageService.Mint.In1Sen_OP_Conn_x_Install='1';
			//去除按钮触发状态
			$scope.showOrHide.principleAlertComponentActive=false;
			//隐藏元件检测界面
			$scope.showOrHide.principleComponent=false;
			//隐藏所有的界面
			$scope.showOrHide.principleAlertOneComponent=false;
			$scope.showOrHide.principleAlertTwoComponent=false;
			$scope.showOrHide.principleAlertThreeComponent=false;
			$scope.showOrHide.principleAlertFourComponent=false;
			$scope.showOrHide.principleAlertFiveComponent=false;
			$scope.showOrHide.principleAlertSixComponent=false;
			//万用表表针归位
			multimeterService.Mdata.multimeterblackRecover();
			multimeterService.Mdata.multimeterredRecover();
		}
	}
	
	//车上位置方法--------------------------------------------------------------------------
	$scope.sysAlertPlace=function(id){
		//记录进度
		recordHistory(id);
		//加上触发状态
		//一个元件每次只允许打开三个弹出框中的一个(所以先关闭所有打开的弹出框)
		$scope.closeComponent();
		$scope.closePlace();
		$scope.closeFail();
		if(sysStay==1){
			//增加触发状态
			$scope.showOrHide.circuitAlertPlaceActive=true;
			//显示车上位置图片
			$scope.showOrHide.circuitPlace=true;
			//改变车上位置图片内容
			$scope.chargeData.circuitPlaceImgSrc=$scope.chargeData.placeImgSrc[sysCircuitAlert-1];
			//打开了元件检测或车上位置或失效模式状态码
			circuitAlertStay=1;
			//打开了同时收回表笔
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//改变万用表热区的显示隐藏状态
			showAHot();
		};
		if(sysStay==2){
			//增加触发状态
			$scope.showOrHide.principleAlertPlaceActive=true;
			//显示车上位置图片
			$scope.showOrHide.principlePlace=true;
			//改变车上位置图片内容
			$scope.chargeData.principlePlaceImgSrc=$scope.chargeData.placeImgSrc[sysPrincipleAlert-1];
		}
	}
	//车上位置关闭方法-----------------
	$scope.closePlace=function(){
		if(sysStay==1){
			//去除按钮触发状态
			$scope.showOrHide.circuitAlertPlaceActive=false;
			//隐藏车上位置图片
			$scope.showOrHide.circuitPlace=false;
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//隐藏了元件检测或车上位置或失效模式状态码
			circuitAlertStay=0;
			//改变万用表热区的显示隐藏状态
			showAHot();
		};
		if(sysStay==2){
			//去除按钮触发状态
			$scope.showOrHide.principleAlertPlaceActive=false;
			//隐藏车上位置图片
			$scope.showOrHide.principlePlace=false;
		}
	}
	
	//失效模式方法---------------------------------------------------------------------------
	$scope.sysAlertFail=function (id){
		//记录进度
		recordHistory(id);
		//一个元件每次只允许打开三个弹出框中的一个(所以先关闭所有打开的弹出框)
		$scope.closeComponent();
		$scope.closePlace();
		$scope.closeFail();
		if(sysStay==1){
			//增加触发状态
			$scope.showOrHide.circuitAlertFailActive=true;
			//打开失效模式界面
			$scope.showOrHide.circuitFail=true;
			$scope.serviceDataPFail=serviceData.PFail['failure'][sysCircuitAlert-1];
			//打开了元件检测或车上位置或失效模式状态码
			circuitAlertStay=1;
			//打开了同时收回表笔
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//改变万用表热区的显示隐藏状态
			showAHot();
		}
		if(sysStay==2){
			//增加触发状态
			$scope.showOrHide.principleAlertFailActive=true;
			//打开失效模式界面
			$scope.showOrHide.principleFail=true;
			$scope.serviceDataPFail=serviceData.PFail['failure'][sysPrincipleAlert-1];
		}
	}
	//失效模式关闭方法-----------------
	$scope.closeFail=function (){
		if(sysStay==1){
			//去除按钮触发状态
			$scope.showOrHide.circuitAlertFailActive=false;
			//打开失效模式界面
			$scope.showOrHide.circuitFail=false;
			if(circuitAlertStay==1){
				//万用表表针归位
				multimeterService.Mdata.multimeterblackRecover();
				multimeterService.Mdata.multimeterredRecover();
			}
			//隐藏了元件检测或车上位置或失效模式状态码
			circuitAlertStay=0;
			//改变万用表热区的显示隐藏状态
			showAHot();
		}
		if(sysStay==2){
			//去除按钮触发状态
			$scope.showOrHide.principleAlertFailActive=false;
			//关闭失效模式界面
			$scope.showOrHide.principleFail=false;
		}
	}
	//元件检测按钮操作===================================================================================================================
	$scope.testMist=function(id){
		if(id==1){
			//控制中心按钮加上样式
			$(".test-btn").removeClass("btn-active");
			$(".mist1").addClass("btn-active");
			//手柄的
			handleRotateTest(-4,-4);
			pageService.Mint.In1ERV_MIST_Button_x_Test='1';
			pageService.Mint.In1ERV_OFF_Button_x_Test='0';
			pageService.Mint.In1ERV_INT_Button_x_Test='0';
			pageService.Mint.In1ERV_Low_Button_x_Test='0';
			pageService.Mint.In1ERV_High_Button_x_Test='0';
			pageService.Mint.In1ERV_Water_Button_x_Test='0';
		}else{
			$scope.testOff();
		}

	}
	$scope.testOff=function(){
		//控制中心按钮加上样式
		$(".test-btn").removeClass("btn-active");
		$(".off1").addClass("btn-active");
		//手柄的
		handleRotateTest(0,0);
		pageService.Mint.In1ERV_MIST_Button_x_Test='0';
		pageService.Mint.In1ERV_OFF_Button_x_Test='1';
		pageService.Mint.In1ERV_INT_Button_x_Test='0';
		pageService.Mint.In1ERV_Low_Button_x_Test='0';
		pageService.Mint.In1ERV_High_Button_x_Test='0';
		pageService.Mint.In1ERV_Water_Button_x_Test='0';
	}
	$scope.testInt=function(){
		//控制中心按钮加上样式
		$(".test-btn").removeClass("btn-active");
		$(".int1").addClass("btn-active");
		//手柄的
		handleRotateTest(4,4);
		pageService.Mint.In1ERV_MIST_Button_x_Test='0';
		pageService.Mint.In1ERV_OFF_Button_x_Test='0';
		pageService.Mint.In1ERV_INT_Button_x_Test='1';
		pageService.Mint.In1ERV_Low_Button_x_Test='0';
		pageService.Mint.In1ERV_High_Button_x_Test='0';
		pageService.Mint.In1ERV_Water_Button_x_Test='0';
	}
	$scope.testLower=function(){
		//控制中心按钮加上样式
		$(".test-btn").removeClass("btn-active");
		$(".lo1").addClass("btn-active");
		//手柄的
		handleRotateTest(8,8);
		pageService.Mint.In1ERV_MIST_Button_x_Test='0';
		pageService.Mint.In1ERV_OFF_Button_x_Test='0';
		pageService.Mint.In1ERV_INT_Button_x_Test='0';
		pageService.Mint.In1ERV_Low_Button_x_Test='1';
		pageService.Mint.In1ERV_High_Button_x_Test='0';
		pageService.Mint.In1ERV_Water_Button_x_Test='0';
	}
	$scope.testHigh=function(){
		//控制中心按钮加上样式
		$(".test-btn").removeClass("btn-active");
		$(".hi1").addClass("btn-active");
		//手柄的
		handleRotateTest(12,12);
		pageService.Mint.In1ERV_MIST_Button_x_Test='0';
		pageService.Mint.In1ERV_OFF_Button_x_Test='0';
		pageService.Mint.In1ERV_INT_Button_x_Test='0';
		pageService.Mint.In1ERV_Low_Button_x_Test='0';
		pageService.Mint.In1ERV_High_Button_x_Test='1';
		pageService.Mint.In1ERV_Water_Button_x_Test='0';
	}
	$scope.testSpray=function(id){
		if(id==1){
			//控制中心按钮加上样式
			$(".test-btn").removeClass("btn-active");
			$(".spray1").addClass("btn-active");
			handleRotateTest(0,0);
			//档位手柄转动
			$(".component-handle").css("background","url(images/component_handle1.png) no-repeat");
			pageService.Mint.In1ERV_MIST_Button_x_Test='0';
			pageService.Mint.In1ERV_OFF_Button_x_Test='0';
			pageService.Mint.In1ERV_INT_Button_x_Test='0';
			pageService.Mint.In1ERV_Low_Button_x_Test='0';
			pageService.Mint.In1ERV_High_Button_x_Test='0';
			pageService.Mint.In1ERV_Water_Button_x_Test='1';
		}else{
			//档位手柄转动
			$(".component-handle").css("background","url(images/component_handle.png) no-repeat");
			$scope.testOff();
		}

	}
	//控制中心按钮操作===================================================================================================================
	//除雾档
	$scope.miststalls=function(id){
		//lock,acc不执行
		if(isRunAnimate==0){
			return;
		}
		//如果是在间歇时度数要置为0
		if(intStopOrPlay==1){
			wiperMotorDeg = 0;
		}
		pageService.Mint.In1ERV_MIST_Button_x_x='1';
		pageService.Mint.In1ERV_OFF_Button_x_x='0';
		pageService.Mint.In1ERV_INT_Button_x_x='0';
		pageService.Mint.In1ERV_Low_Button_x_x='0';
		pageService.Mint.In1ERV_High_Button_x_x='0';
		pageService.Mint.In1ERV_Water_Button_x_x='0';
		//mist档位和喷水档位松开以后就打到1了，这样的话转一圈就停了
		wiperMotorStop=0;
		//其他档位的时候间歇档要置0
		intStopOrPlay=0;
		//其他档位的时候高速档要置0
		hiStopOrPlay=0;
		//1代表按下，0代表松开
		if(id==1){
			//档位手柄转动
			handleRotate(-4,-2);
			//线路初始化
			$scope.stallsInt();
			//刮水电动机开始旋转
			$scope.wiperRotates(1);
			//刮水器运转
			$scope.wiperSwing();
			//控制中心按钮加上样式
			$(".handle-btn").removeClass("btn-active");
			$(".mist").addClass("btn-active");
			//原理线路
			$('.line-1-1').css("background","#f00");
			//电路线路
			$(".circuit-dash-link1,.circuit-mist-dash,.circuit-line3").attr("stroke","#f00");
		}else{
			//刚好回到初始位置就立马停止转，否则就转到初始位置再停止
			$scope.offstalls();
		}

	}
	//低速
	$scope.loStalls=function(){
		//alert(isRunAnimate)
		//lock,acc不执行
		if(isRunAnimate==0){
			return;
		}
		//如果是在间歇时度数要置为0
		if(intStopOrPlay==1){
			wiperMotorDeg = 0;
		}
		pageService.Mint.In1ERV_MIST_Button_x_x='0';
		pageService.Mint.In1ERV_OFF_Button_x_x='0';
		pageService.Mint.In1ERV_INT_Button_x_x='0';
		pageService.Mint.In1ERV_Low_Button_x_x='1';
		pageService.Mint.In1ERV_High_Button_x_x='0';
		pageService.Mint.In1ERV_Water_Button_x_x='0';
		//其他档位的时候间歇档要置0
		intStopOrPlay=0;
		//其他档位的时候高速档要置0
		hiStopOrPlay=0;
		//mist档位和喷水档位松开以后就打到1了，这样的话转一圈就停了
		wiperMotorStop=0;
		//刮水器运转
		$scope.wiperSwing();
		//档位手柄转动
		handleRotate(8,3);
		//电路线路状态初始化
		$scope.stallsInt();
		//刮水电动机开始旋转
		$scope.wiperRotates(1);
		$(".handle-btn").removeClass("btn-active");
		$(".lo").addClass("btn-active");
		//原理线路
		$('.line-1-1').css("background","#f00");
		//电路线路
		$(".circuit-dash-link1,.circuit-lower-dash,.circuit-line3").attr("stroke", "#f00");

	}
	//高速
	$scope.hiStalls=function(){
		//lock,acc不执行
		if(isRunAnimate==0){
			return;
		}
		//如果是在间歇时度数要置为0
		if(intStopOrPlay==1){
			wiperMotorDeg = 0;
		}
		pageService.Mint.In1ERV_MIST_Button_x_x='0';
		pageService.Mint.In1ERV_OFF_Button_x_x='0';
		pageService.Mint.In1ERV_INT_Button_x_x='0';
		pageService.Mint.In1ERV_Low_Button_x_x='0';
		pageService.Mint.In1ERV_High_Button_x_x='1';
		pageService.Mint.In1ERV_Water_Button_x_x='0';
		//其他档位的时候间歇档要置0
		intStopOrPlay=0;
		//其他档位的时候高速档要置0
		hiStopOrPlay=1;
		//mist档位和喷水档位松开以后就打到1了，这样的话转一圈就停了
		wiperMotorStop=0;
		//按钮状态
		$(".handle-btn").removeClass("btn-active");
		$(".hi").addClass("btn-active");
		//电路线路初始化
		$scope.stallsInt();
		//档位手柄转动
		handleRotate(12,4);
		//故障
		if(goCheckStay==1){
			//电路一处断开
			$(".circuit-manu").attr("stroke","none");
			//电路线路
			$(".circuit-dash-link1,.circuit-high-dash1").attr("stroke", "#f00");
			//原理线路
			$('.line-1-1').css("background","#000");
			//雨刷运动停止
			$scope.animateStop();
			//电机运动停止
			clearInterval(wiperMotorTimer);
			return ;
		}
		//刮水电动机开始旋转,加上高速
		$scope.wiperRotates(1);
		//刮水器运转
		$scope.wiperSwing();
		//原理线路
		$('.line-1-1').css("background","#f00");
		//电路线路
		$(".circuit-dash-link1,.circuit-high-dash,.circuit-line4").attr("stroke", "#f00");
	}
	//off档
	$scope.offstalls=function(){

		pageService.Mint.In1ERV_MIST_Button_x_x='0';
		pageService.Mint.In1ERV_OFF_Button_x_x='1';
		pageService.Mint.In1ERV_INT_Button_x_x='0';
		pageService.Mint.In1ERV_Low_Button_x_x='0';
		pageService.Mint.In1ERV_High_Button_x_x='0';
		pageService.Mint.In1ERV_Water_Button_x_x='0';
		//线路初始化
		$scope.stallsInt();
		//原理线路
		$('.line-1-1,.line-1-2,.line-1-3').css("background","#000");
		//档位手柄转动
		handleRotate(0,0);
		//控制中心按钮加上样式
		$(".handle-btn").removeClass("btn-active");
		$(".off").addClass("btn-active");//等于1时就停止了
		wiperMotorStop=1;

		//只要不在0或者360度的时候线路变红
		if(wiperMotorDeg!=0&&wiperMotorDeg!=360){
			//在间歇档位是运转的时候
			if(intStopOrPlay==0){
				//intStopOrPlay=1;
				$scope.wiperRotates(1);
				//刮水器运转
				$scope.wiperSwing();
				//电路线路
				$(".circuit-dash-link4,.circuit-off-dash,.circuit-line1,.circuit-line3,.circuit-line-a1").attr("stroke","#f00");
				$(".circuit-switch2").attr({"x2":"297.507","stroke":"#f00"});
			}else{
				wiperMotorDeg=0;
				clearInterval(wiperMotorTimer);
			}
		}
		if(wiperMotorDeg==0||wiperMotorDeg==360){
			clearInterval(wiperMotorTimer);
		}

	}
	//int间歇档
	$scope.intstalls=function(){
		//lock,acc不执行
		if(isRunAnimate==0){
			return;
		}
		pageService.Mint.In1ERV_MIST_Button_x_x='0';
		pageService.Mint.In1ERV_OFF_Button_x_x='0';
		pageService.Mint.In1ERV_INT_Button_x_x='1';
		pageService.Mint.In1ERV_Low_Button_x_x='0';
		pageService.Mint.In1ERV_High_Button_x_x='0';
		pageService.Mint.In1ERV_Water_Button_x_x='0';
		//一点击间歇档也要马上置0
		intStopOrPlay=0;
		//其他档位的时候高速档要置0
		hiStopOrPlay=0;
		//mist档位和喷水档位松开以后就打到1了，这样的话转一圈就停了
		wiperMotorStop=0;
		//档位手柄转动
		handleRotate(4,2);
		//电路线路初始化
		$scope.stallsInt();
		//按钮状态
		$(".handle-btn").removeClass("btn-active");
		$(".int").addClass("btn-active");
		//刮水电动机开始旋转,加上高速
		$scope.wiperRotates(0);
	}

//间歇当第一步
	$scope.intStep1=function(){
		$scope.stallsInt();
		$(".circuit-line1,.circuit-line3,.circuit-line-a1").attr("stroke","#000");
		//step1
		$(".circuit-int-step1,.circuit-line-b1").attr("stroke","#f00");
		$(".circuit-line-b2").attr("stroke","#817325");
		$(".circuit-dash-link5,.circuit-dash-link7,.circuit-int-dash-g").attr("stroke","#1AD041");
		//step2
		$(".circuit-switch2").attr({"x2":"287.507","stroke":"#f00"});
		$(".circuit-int-step2").attr("stroke","#f00");
		$(".circuit-dash-link4,.circuit-int-dash,.circuit-line3").attr("stroke","#f00");
		//原理线路
		$('.line-1-1').css("background","#f00");
	}
//间歇当第二步
	$scope.intStep2=function(){
		$scope.stallsInt();
		$(".circuit-switch2").attr({"x2":"297.507","stroke":"#f00"});
		$(".circuit-dash-link4,.circuit-int-dash,.circuit-line1,.circuit-line3,.circuit-line-a1").attr("stroke","#f00");
		$(".circuit-dash-link5,.circuit-dash-link7,.circuit-int-dash-g").attr("stroke","#1AD041");
		//原理线路
		$('.line-1-1').css("background","#f00");

	}
	//喷水档位
	$scope.waterStalls=function(id){
		//lock,acc不执行
		if(isRunAnimate==0){
			return;
		}
		//如果是在间歇时度数要置为0
		if(intStopOrPlay==1){
			wiperMotorDeg = 0;
		}
		pageService.Mint.In1ERV_MIST_Button_x_x='0';
		pageService.Mint.In1ERV_OFF_Button_x_x='0';
		pageService.Mint.In1ERV_INT_Button_x_x='0';
		pageService.Mint.In1ERV_Low_Button_x_x='0';
		pageService.Mint.In1ERV_High_Button_x_x='0';
		pageService.Mint.In1ERV_Water_Button_x_x='1';
		//mist档位和喷水档位松开以后就打到1了，这样的话转一圈就停了
		wiperMotorStop=0;
		//一点击间歇档也要马上置0
		intStopOrPlay=0;
		//其他档位的时候间歇档要置0
		hiStopOrPlay=0;
		//1代表按下，0代表松开
		if(id==1) {

			//线路初始化
			$scope.stallsInt();
			//档位手柄转动
			$(".principle-handle").css("background","url(images/principle_handle1.png) no-repeat");
			//手柄
			$(".wiper-handle").css("background","url(images/wiper_handle1.png) no-repeat");
			//按钮变化状态
			$(".handle-btn").removeClass("btn-active");
			$(".spray").addClass("btn-active");
			//原理线路
			$('.line-1-2,.line-1-3').css("background","#f00");
			$('.line-1-1').css("background","#f00");
			//step1 and step2
			sprayStep1();
			//喷水
			$(".principle-water1,.principle-water2").show();
			//刮水电动机开始旋转,加上高速
			$scope.wiperRotates(1);
			//刮水器运转
			$scope.wiperSwing();
		}else{
			//档位手柄转动
			$(".principle-handle").css("background","url(images/principle_handle.png) no-repeat");
			//手柄
			$(".wiper-handle").css("background","url(images/wiper_handle.png) no-repeat");
			//不喷水
			$(".principle-water1,.principle-water2").hide();
			$scope.offstalls();

		}
	}
	//刮水器运动
	$scope.wiperSwing=function(){
		pageService.Mint.In1ERV_Wiper_Sport_x_x='1';
		function _rotate(){
			//余数为0的情况并且是高速的情况下要加速为2
			centerMotorDeg=centerMotorDeg+1;

			if(centerMotorDeg==1){
				wiperDeg=-50
			}
			if(centerMotorDeg==2){
				wiperDeg=-49
			}
			if(centerMotorDeg==3){//4
				wiperDeg=-48
			}
			if(centerMotorDeg==5){//4
				wiperDeg=-47
			}
			if(centerMotorDeg==7){//4
				wiperDeg=-46
			}
			if(centerMotorDeg==9){//4
				wiperDeg=-45
			}
			if(centerMotorDeg==11){//4
				wiperDeg=-44
			}
			if(centerMotorDeg==13){//4
				wiperDeg=-43
			}
			if(centerMotorDeg==15){//4
				wiperDeg=-41
			}
			if(centerMotorDeg==17){//4
				wiperDeg=-40
			}
			if(centerMotorDeg==19){//4
				wiperDeg=-39
			}
			if(centerMotorDeg==21){//4
				wiperDeg=-38
			}
			if(centerMotorDeg==23){//4
				wiperDeg=-37
			}
			if(centerMotorDeg==25){//4
				wiperDeg=-36
			}
			if(centerMotorDeg==27){//4
				wiperDeg=-35
			}

			if(centerMotorDeg==29){//4
				wiperDeg=-34
			}

			if(centerMotorDeg==31){//4
				wiperDeg=-33
			}
			if(centerMotorDeg==33){//4
				wiperDeg=-32
			}
			if(centerMotorDeg==35){//4
				wiperDeg=-31
			}
			if(centerMotorDeg==37){//4
				wiperDeg=-30
			}
			if(centerMotorDeg==39){//4
				wiperDeg=-29
			}
			if(centerMotorDeg==41){//4
				wiperDeg=-28
			}
			if(centerMotorDeg==43){//4
				wiperDeg=-27
			}
			if(centerMotorDeg==45){//4
				wiperDeg=-26
			}
			if(centerMotorDeg==47){//4
				wiperDeg=-25
			}
			if(centerMotorDeg==48){//4
				wiperDeg=-24
			}
			if(centerMotorDeg==49){//4
				wiperDeg=-23
			}
			if(centerMotorDeg==50){//4
				wiperDeg=-22
			}
			if(centerMotorDeg==51){//4
				wiperDeg=-21
			}
			if(centerMotorDeg==52){//4
				wiperDeg=-20
			}
			if(centerMotorDeg==54){//4
				wiperDeg=-19
			}
			if(centerMotorDeg==55){//4
				wiperDeg=-18
			}
			if(centerMotorDeg==56){//4
				wiperDeg=-17
			}
			if(centerMotorDeg==57){//4
				wiperDeg=-16
			}
			if(centerMotorDeg==58){//4
				wiperDeg=-15
			}
			if(centerMotorDeg==59){//4
				wiperDeg=-14
			}
			if(centerMotorDeg==61){//4
				wiperDeg=-13
			}
			if(centerMotorDeg==63){//4
				wiperDeg=-12
			}
			if(centerMotorDeg==65){//4
				wiperDeg=-11
			}
			if(centerMotorDeg==67){//4
				wiperDeg=-10
			}
			if(centerMotorDeg==69){//4
				wiperDeg=-9
			}
			if(centerMotorDeg==70){//4
				wiperDeg=-8
			}
			if(centerMotorDeg==71){//4
				wiperDeg=-7
			}
			if(centerMotorDeg==72){//4
				wiperDeg=-6
			}
			if(centerMotorDeg==73){//4
				wiperDeg=-5
			}
			if(centerMotorDeg==74){//4
				wiperDeg=-4
			}
			if(centerMotorDeg==75){//4
				wiperDeg=-3
			}
			if(centerMotorDeg==76){//4
				wiperDeg=-2
			}
			if(centerMotorDeg==77){//4
				wiperDeg=-1
			}
			if(centerMotorDeg==78){//4
				wiperDeg=0
			}
			if(centerMotorDeg==80){//4
				wiperDeg=1
			}
			if(centerMotorDeg==82){//4
				wiperDeg=2
			}
			if(centerMotorDeg==84){//4
				wiperDeg=3
			}
			if(centerMotorDeg==85){//4
				wiperDeg=4
			}
			if(centerMotorDeg==86){//4
				wiperDeg=5
			}
			if(centerMotorDeg==87){//4
				wiperDeg=6
			}
			if(centerMotorDeg==88){//4
				wiperDeg=7
			}
			if(centerMotorDeg==90){//4
				wiperDeg=8
			}
			if(centerMotorDeg==92){//4
				wiperDeg=9
			}
			if(centerMotorDeg==94){//4
				wiperDeg=10
			}
			if(centerMotorDeg==96){//4
				wiperDeg=11
			}
			if(centerMotorDeg==98){//4
				wiperDeg=12
			}
			if(centerMotorDeg==100){//4
				wiperDeg=13
			}
			if(centerMotorDeg==101){//4
				wiperDeg=14
			}
			if(centerMotorDeg==102){//4
				wiperDeg=15
			}
			if(centerMotorDeg==103){//4
				wiperDeg=16
			}
			if(centerMotorDeg==104){//4
				wiperDeg=17
			}
			if(centerMotorDeg==105){//4
				wiperDeg=18
			}
			if(centerMotorDeg==106){//4
				wiperDeg=19
			}
			if(centerMotorDeg==108){//4
				wiperDeg=20
			}
			if(centerMotorDeg==110){//4
				wiperDeg=21
			}
			if(centerMotorDeg==112){//4
				wiperDeg=22
			}
			if(centerMotorDeg==113){//4
				wiperDeg=23
			}
			if(centerMotorDeg==114){//4
				wiperDeg=24
			}
			if(centerMotorDeg==115){//4
				wiperDeg=25
			}
			if(centerMotorDeg==117){//4
				wiperDeg=26
			}
			if(centerMotorDeg==119){//4
				wiperDeg=27
			}
			if(centerMotorDeg==120){//4
				wiperDeg=28
			}
			if(centerMotorDeg==122){//4
				wiperDeg=29
			}
			if(centerMotorDeg==124){//4
				wiperDeg=30
			}if(centerMotorDeg==126){//4
				wiperDeg=31
			}
			if(centerMotorDeg==127){//4
				wiperDeg=32
			}
			if(centerMotorDeg==128){//4
				wiperDeg=33
			}
			if(centerMotorDeg==130){//4
				wiperDeg=34
			}
			if(centerMotorDeg==132){//4
				wiperDeg=35
			}
			if(centerMotorDeg==134){//4
				wiperDeg=36
			}
			if(centerMotorDeg==136){//4
				wiperDeg=37
			}
			if(centerMotorDeg==138){//4
				wiperDeg=38
			}
			if(centerMotorDeg==140){//4
				wiperDeg=39
			}
			if(centerMotorDeg==142){//4
				wiperDeg=40
			}
			if(centerMotorDeg==143){//4
				wiperDeg=41
			}
			if(centerMotorDeg==144){//4
				wiperDeg=42
			}
			if(centerMotorDeg==146){//4
				wiperDeg=43
			}
			if(centerMotorDeg==148){//4
				wiperDeg=44
			}
			if(centerMotorDeg==150){//4
				wiperDeg=45
			}
			if(centerMotorDeg==152){//4
				wiperDeg=45
			}
			if(centerMotorDeg==153){//4
				wiperDeg=46
			}
			if(centerMotorDeg==154){//4
				wiperDeg=47
			}
			if(centerMotorDeg==155){//4
				wiperDeg=48
			}
			if(centerMotorDeg==157){//4
				wiperDeg=49
			}
			if(centerMotorDeg==159){//4
				wiperDeg=50
			}
			if(centerMotorDeg==198){//、、、、、、、
				wiperDeg=49
			}
			if(centerMotorDeg==199){//
				wiperDeg=48
			}
			if(centerMotorDeg==200){//
				wiperDeg=47
			}
			if(centerMotorDeg==202){//
				wiperDeg=46
			}
			if(centerMotorDeg==204){//
				wiperDeg=45
			}
			if(centerMotorDeg==206){//
				wiperDeg=44
			}
			if(centerMotorDeg==208){//
				wiperDeg=43
			}
			if(centerMotorDeg==210){//
				wiperDeg=42
			}
			if(centerMotorDeg==212){//
				wiperDeg=41
			}
			if(centerMotorDeg==214){//
				wiperDeg=40
			}
			if(centerMotorDeg==216){//
				wiperDeg=39
			}
			if(centerMotorDeg==217){//
				wiperDeg=38
			}
			if(centerMotorDeg==219){//
				wiperDeg=37
			}
			if(centerMotorDeg==220){//
				wiperDeg=36
			}
			if(centerMotorDeg==221){//
				wiperDeg=35
			}
			if(centerMotorDeg==223){//
				wiperDeg=34
			}
			if(centerMotorDeg==225){//
				wiperDeg=33
			}
			if(centerMotorDeg==226){//
				wiperDeg=32
			}
			if(centerMotorDeg==228){//
				wiperDeg=31
			}
			if(centerMotorDeg==229){//
				wiperDeg=30
			}
			if(centerMotorDeg==230){//
				wiperDeg=29
			}
			if(centerMotorDeg==232){//
				wiperDeg=28
			}
			if(centerMotorDeg==234){//
				wiperDeg=27
			}
			if(centerMotorDeg==236){//
				wiperDeg=26
			}
			if(centerMotorDeg==238){//
				wiperDeg=25
			}
			if(centerMotorDeg==240){//
				wiperDeg=24
			}
			if(centerMotorDeg==241){//
				wiperDeg=23
			}
			if(centerMotorDeg==242){//
				wiperDeg=22
			}
			if(centerMotorDeg==243){//
				wiperDeg=21
			}
			if(centerMotorDeg==244){//
				wiperDeg=20
			}
			if(centerMotorDeg==245){//
				wiperDeg=19
			}
			if(centerMotorDeg==246){//
				wiperDeg=18
			}
			if(centerMotorDeg==247){//
				wiperDeg=17
			}
			if(centerMotorDeg==248){//
				wiperDeg=16
			}
			if(centerMotorDeg==249){//
				wiperDeg=15
			}
			if(centerMotorDeg==251){//
				wiperDeg=14
			}
			if(centerMotorDeg==253){//
				wiperDeg=13
			}
			if(centerMotorDeg==255){//
				wiperDeg=12
			}
			if(centerMotorDeg==256){//
				wiperDeg=11
			}
			if(centerMotorDeg==257){//
				wiperDeg=10
			}
			if(centerMotorDeg==259){//
				wiperDeg=9
			}
			if(centerMotorDeg==261){//
				wiperDeg=8
			}
			if(centerMotorDeg==262){//
				wiperDeg=7
			}
			if(centerMotorDeg==263){//
				wiperDeg=6
			}
			if(centerMotorDeg==264){//
				wiperDeg=5
			}
			if(centerMotorDeg==265){//
				wiperDeg=4
			}
			if(centerMotorDeg==266){//
				wiperDeg=3
			}
			if(centerMotorDeg==267){//
				wiperDeg=2
			}
			if(centerMotorDeg==268){//
				wiperDeg=1
			}
			if(centerMotorDeg==269){//
				wiperDeg=0
			}
			if(centerMotorDeg==270){//
				wiperDeg=0
			}
			if(centerMotorDeg==271){//
				wiperDeg=-1
			}
			if(centerMotorDeg==272){//
				wiperDeg=-2
			}
			if(centerMotorDeg==273){//
				wiperDeg=-3
			}
			if(centerMotorDeg==274){//
				wiperDeg=-4
			}
			if(centerMotorDeg==276){//
				wiperDeg=-5
			}
			if(centerMotorDeg==278){//
				wiperDeg=-6
			}
			if(centerMotorDeg==279){//
				wiperDeg=-7
			}
			if(centerMotorDeg==280){//
				wiperDeg=-8
			}
			if(centerMotorDeg==281){//
				wiperDeg=-9
			}
			if(centerMotorDeg==282){//
				wiperDeg=-10
			}
			if(centerMotorDeg==283){//
				wiperDeg=-11
			}
			if(centerMotorDeg==284){//
				wiperDeg=-12
			}
			if(centerMotorDeg==285){//
				wiperDeg=-13
			}
			if(centerMotorDeg==286){//
				wiperDeg=-14
			}
			if(centerMotorDeg==287){//
				wiperDeg=-15
			}
			if(centerMotorDeg==288){//
				wiperDeg=-16
			}
			if(centerMotorDeg==290){//
				wiperDeg=-17
			}
			if(centerMotorDeg==291){//
				wiperDeg=-18
			}
			if(centerMotorDeg==292){//
				wiperDeg=-19
			}
			if(centerMotorDeg==294){//
				wiperDeg=-20
			}
			if(centerMotorDeg==295){//
				wiperDeg=-21
			}
			if(centerMotorDeg==296){//
				wiperDeg=-22
			}
			/*	if(centerMotorDeg==297){//
			 wiperDeg=-23
			 }*/
			if(centerMotorDeg==298){//
				wiperDeg=-23
			}
			if(centerMotorDeg==299){//
				wiperDeg=-24
			}
			if(centerMotorDeg==300){//
				wiperDeg=-25
			}
			if(centerMotorDeg==301){//
				wiperDeg=-26
			}
			if(centerMotorDeg==304){//
				wiperDeg=-27
			}
			if(centerMotorDeg==306){//
				wiperDeg=-28
			}
			if(centerMotorDeg==308){//
				wiperDeg=-29
			}
			if(centerMotorDeg==310){//
				wiperDeg=-30
			}
			if(centerMotorDeg==312){//
				wiperDeg=-31
			}
			if(centerMotorDeg==313){//
				wiperDeg=-32
			}
			if(centerMotorDeg==314){//
				wiperDeg=-33
			}
			if(centerMotorDeg==315){//
				wiperDeg=-34
			}
			if(centerMotorDeg==317){//
				wiperDeg=-35
			}
			if(centerMotorDeg==319){//
				wiperDeg=-36
			}
			if(centerMotorDeg==321){//
				wiperDeg=-37
			}
			if(centerMotorDeg==323){//
				wiperDeg=-38
			}
			if(centerMotorDeg==325){//
				wiperDeg=-39
			}
			if(centerMotorDeg==327){//
				wiperDeg=-40
			}
			if(centerMotorDeg==329){//
				wiperDeg=-41
			}
			if(centerMotorDeg==331){//
				wiperDeg=-42
			}
			if(centerMotorDeg==334){//
				wiperDeg=-43
			}
			if(centerMotorDeg==337){//
				wiperDeg=-44
			}
			if(centerMotorDeg==341){//
				wiperDeg=-45
			}
			if(centerMotorDeg==344){//
				wiperDeg=-46
			}
			if(centerMotorDeg==347){//
				wiperDeg=-47
			}
			if(centerMotorDeg==350){//
				wiperDeg=-48
			}
			if(centerMotorDeg==354){//
				wiperDeg=-49
			}
			if(centerMotorDeg==358){//
				wiperDeg=-50
			}
			if(centerMotorDeg>=360){
				centerMotorDeg = 0;
				wiperDeg=-50;
			}
			//角度和时间之间的关系,指的是摇杆的旋转角度，这里用的钟摆的周期计算
			//wiperDeg=50*Math.sin(Math.PI/1.8*(_centerDeg/100));
			var _wiperDeg;

			_wiperDeg=wiperDeg+50;
			//X3=(X1-X2)cosθ-(Y1-Y2)sinθ+X2，圆的轨迹
			//Y3=(X1-X2)sinθ+(Y1-Y2)cosθ+Y2
			var x=(25)*Math.cos(_wiperDeg*Math.PI/180)-(24)*Math.sin(_wiperDeg*Math.PI/180)+284;
			var y=(25)*Math.sin(_wiperDeg*Math.PI/180)+(24)*Math.cos(_wiperDeg*Math.PI/180)+305;
			var x1=(26)*Math.cos(centerMotorDeg*Math.PI/180)-(3)*Math.sin(centerMotorDeg*Math.PI/180)+364;
			var y1=(3)*Math.cos(centerMotorDeg*Math.PI/180)+(26)*Math.sin(centerMotorDeg*Math.PI/180)+331;
			if(centerMotorDeg<=185||centerMotorDeg>350||centerMotorDeg==0){
				//wiperLeverDeg=10/180*centerMotorDeg;
				wiperLeverDeg=-180*Math.atan((x-x1)/(y-y1))/Math.PI+90;
			}else {
				//wiperLeverDeg=-30/180*(centerMotorDeg-180);
				wiperLeverDeg=-180*Math.atan((x-x1)/(y-y1))/Math.PI-90;
			}

			//180*Math.asin(0.5)/pai
			$(".center-motor").css({"transform":"rotate("+centerMotorDeg+"deg)","-ms-transform":"rotate("+centerMotorDeg+"deg)"});
			$(".left-wiper").css({"transform":"rotate("+(wiperDeg-2)+"deg)","-ms-transform":"rotate("+(wiperDeg-2)+"deg)"});
			$(".right-wiper").css({"transform":"rotate("+(wiperDeg+2)+"deg)","-ms-transform":"rotate("+(wiperDeg+2)+"deg)"});
			$(".left-lever").css({"top":(y1-2),"left":(x1-84)});
			$(".right-lever").css({"top":(y1-2),"left":(x1-84)});
			$(".red").css({"top":y,"left":x});
			$(".red1").css({"top":y1,"left":x1});
			$(".left-lever").css({"transform":"rotate("+wiperLeverDeg+"deg)","-ms-transform":"rotate("+wiperLeverDeg+"deg)"});
			$(".right-lever").css({"transform":"rotate("+(-(wiperLeverDeg))+"deg)","-ms-transform":"rotate("+(-(wiperLeverDeg))+"deg)"});

		}
		//刮水电动机回调函数
		function _time(f,time){
			if(swingTimer){clearInterval(swingTimer)}
			return function back(){
				if(swingTimer){clearInterval(swingTimer)}
				swingTimer=setTimeout(function(){
					f();
					back();
				},time)
			}
		}
		if(hiStopOrPlay==1){
			_time(_rotate, 5)();
		}else {
			_time(_rotate, 10)();
		}
	}
	//刮水运动停止
	$scope.animateStop=function(){
		clearInterval(swingTimer);
		if(wiperMotorDeg==360||wiperMotorDeg==0){
			//模型
			pageService.Mint.In1ERV_Wiper_Sport_x_x='0';
		}
		//让电动机的螺旋钉子也停止转动
		$(".principle-scroll").stop();
	}
	//刮水转动，1代表正常的，0代表间歇的
	$scope.wiperRotates=function(id){
		scroll();
		//线路1变黑色
		$(".circuit-line1").attr("stroke","#000");

		function _rotate(){

			wiperMotorDeg=wiperMotorDeg+1;
			if(wiperMotorDeg==360) {
				wiperMotorDeg = 0;
				if(pageService.Mint.In1ERV_INT_Button_x_x=='1'){
					//为间歇所准备的参数
					if(intStopOrPlay==1){
						intStopOrPlay=0;
					}else{
						intStopOrPlay=1;
					}
				}

			}
			//alert()
			$('.wiper-motor,.principle-motor,.principle-motor1').css({"transform":"rotate("+wiperMotorDeg+"deg)","-ms-transform":"rotate("+wiperMotorDeg+"deg)"});
		}
		//间歇第三步
		function _rotates(){
			wiperMotorDeg=wiperMotorDeg+1;
			if(wiperMotorDeg==360) {
				wiperMotorDeg = 0;
				//为间歇所准备的参数
				if(intStopOrPlay==1){
					//刮水器运转
					$scope.wiperSwing();
					intStopOrPlay=0;
				}else{
					//原理电动机停下来
					$scope.animateStop();
					intStopOrPlay=1;
				}
			}
		}
		//要为间歇先设置一个空函数
		function empty(){
			//wiperMotorDeg = 0;
			//刮水器运转
			$scope.wiperSwing();
		}
		//刮水电动机回调函数
		function _time(f,time){
			if(wiperMotorTimer){clearInterval(wiperMotorTimer)}
			return function back(){
				if(wiperMotorTimer){clearInterval(wiperMotorTimer)}
				wiperMotorTimer=setTimeout(function(){
					f();
					back();
					//console.log(wiperMotorDeg);
					if(wiperMotorDeg==360||wiperMotorDeg==0) {
						//碰到松开需要清除定时器，让电动机停止转动
						if(wiperMotorStop==1){
							clearInterval(wiperMotorTimer);
							//原理电动机停下来
							$scope.animateStop();
							//线路初始化
							$scope.stallsInt();
							//停止转动的话线路1就变棕色
							$(".circuit-line1").attr("stroke","#817325");
							//原理线路
							//$('.line-1-1,.line-1-2,.line-1-3').css("background","#000");
							wiperMotorStop=0;
						}
					}
				},time)
			}
		}
		//刮水电动机回调函数，间歇需求
		function _times(f,time){
			if(wiperMotorTimer){clearTimeout(wiperMotorTimer)}
			return function back(){
				if(wiperMotorTimer){clearTimeout(wiperMotorTimer)}
				wiperMotorTimer=setTimeout(function(){
					f();
					back();
					//console.log(wiperMotorDeg);
					//intStopOrPlay为1时不转间歇，为0时转动
					if(intStopOrPlay==1){
						_times(_rotates,10)();
						//线路初始化,off档加上绿色
						$scope.stallsInt();
						//原理线路1变黑
						$('.line-1-1').css("background","#000");
						//线路1变棕色
						$(".circuit-line1").attr("stroke","#817325");
						//原理电动机停下来
						$scope.animateStop();
					}else{
						_times(_rotate,10)();
						//在0-180度时执行intStep1
						if(wiperMotorDeg>=0&&wiperMotorDeg<180){
							//加上step1
							$scope.intStep1();
						}else if(wiperMotorDeg>=180&&wiperMotorDeg<360){
							//线路初始化,off档加上绿色
							$scope.intStep2();
						}

					}

					if(wiperMotorDeg==360||wiperMotorDeg==0) {
						//碰到off档需要清除定时器，让电动机停止转动
						if(wiperMotorStop==1){
							clearInterval(wiperMotorTimer);
							//原理电动机停下来
							$scope.animateStop();
							//线路初始化
							$scope.stallsInt();
							//停止转动的话线路1就变棕色
							$(".circuit-line1").attr("stroke","#817325");
							wiperMotorStop=0;
						}
						//在lock档位增加一个转完这圈再停下来
						if($rootScope.isRun==0){
							//原理电动机停下来
							$scope.animateStop();
							clearInterval(wiperMotorTimer);
							wiperMotorStop=0;
						}
					}

				},time)
			}
		}
		//为0是间歇
		if(id==1){
			if(hiStopOrPlay==1){
				_time(_rotate, 5)();
			}else {
				_time(_rotate, 10)();
			}
		}else{
			_times(empty,10)();
		}

	}
	//点击lock-----------------------------------------
	//雨刷档位初始化
	$scope.stallsInt=function(){
		//$(".off").addClass("btn-active");
		$(".circuit-dash").attr("stroke","none");
		$(".circuit-stalls").attr("stroke","#000");
		//开关和线圈初始化
		$(".circuit-switch2").attr({"x2":"297.507","stroke":"#000"});
		if(goCheckStay==1) {
			//电路一处断开
			$(".circuit-manu").attr("stroke", "none");
		}
	}
	//acc和lock状态 （初始化 系统电路 动画状态）
	$rootScope.circuitAnimateInitialize=function(){
		$(".line-animate-flow span").stop();
		//所有线路先初始化
		$(".line-animate-flow .height").css("height","0px");
		$(".line-animate-flow .width").css("width","0px");
		//开关和线圈初始化
		$(".circuit-switch1").attr({"x2":"750.68","stroke":"#000"});
		$(".circuit-on,.circuit-on-line2,.circuit-on-line1").attr("stroke","#000");
		$(".circuit-dash").attr("stroke","none");
		$(".circuit-stalls").attr("stroke","#000");
		//开关和线圈初始化
		$(".circuit-switch2").attr({"x2":"297.507","stroke":"#000"});
		if(pageService.Mint.In1ERV_OFF_Button_x_x=='0'&&pageService.Mint.In1ERV_INT_Button_x_x!='1'){
			//清除电动机定时器
			clearInterval(wiperMotorTimer);
			//刮水运动停止
			$scope.animateStop();
		}else{
			if(wiperMotorDeg!=0){
				//电路线路
				$(".circuit-dash-link4,.circuit-off-dash,.circuit-line1,.circuit-line3,.circuit-line-a1").attr("stroke","#f00");
				$(".circuit-switch2").attr({"x2":"297.507","stroke":"#f00"});
			}
		}
		if(goCheckStay==1) {
			//电路一处断开
			$(".circuit-manu").attr("stroke", "none");
		}
	}
	//点击进入故障------------------------------------------
	$scope.goMalfunctionAnimate=function(){
		//电路一处断开
		$(".circuit-manu").attr("stroke","none");
		if(isRunAnimate==1||isRunAnimate==2&&hiStopOrPlay==1){
			//雨刷运动停止
			$scope.animateStop();
			//
			clearInterval(wiperMotorTimer);
			//电路线路
			$(".circuit-high-dash2,.circuit-line4").attr("stroke", "#000");
			$(".circuit-high-dash3").attr("stroke", "none");
			//原理线路
			$('.line-1-1').css("background","#000");
		}
	}
	//清除故障1
	$scope.clearMalfunctionAnimate=function(){
		//在on，start档时才会闭合变红,高速
		if(isRunAnimate==1||isRunAnimate==2&&hiStopOrPlay==1){
			//电路断开处闭合
			$(".circuit-manu").attr("stroke","#f00");
			//
			$scope.hiStalls();
		}else{
			//电路断开处闭合
			$(".circuit-manu").attr("stroke","#000");
		}
	}
	//点开三个车锁面板   原理动画和电路动画通用======================================================================================================
	var zIndex=14;
	$scope.openSwitchPanel=function(val){
		//打开门控开关
		if(val==1){
			$(".wifi-switch-panel,.key-switch-panel").css("z-index",(zIndex-1));
			$(".door-switch-panel").removeClass("hide-important").css("z-index","16");
			$(".door-switch").parent().addClass("active");
		}
		//打遥控器
		if(val==2){
			$(".door-switch-panel,.key-switch-panel").css("z-index",(zIndex-1));
			$(".wifi-switch-panel").removeClass("hide-important").css("z-index","16");
			$(".wifi-switch").parent().addClass("active");
		}
		//打开车门锁
		if(val==3){
			$(".wifi-switch-panel,.door-switch-panel").css("z-index",(zIndex-1));
			$(".key-switch-panel").removeClass("hide-important").css("z-index","16");
			$(".key-switch").parent().addClass("active");
		}
	}
	$scope.closeSwitchPanel=function(val){
		//关闭门控开关
		if(val==1){
			$(".door-switch-panel").addClass("hide-important");
			$(".door-switch").parent().removeClass("active");
		}
		//关闭遥控器
		if(val==2){
			$(".wifi-switch-panel").addClass("hide-important");
			$(".wifi-switch").parent().removeClass("active");
		}
		//关闭门锁
		if(val==3){
			$(".key-switch-panel").addClass("hide-important");
			$(".key-switch").parent().removeClass("active");
		}
	}

	//弹出电阻不可用弹出框===============================================================================================
	$rootScope.createResistanceWarn= function(val){
		if($(".resistanceWarn").length>0){
			return;
		}
		$(".alert-container").html($compile('<div class="resistanceWarn z-index-100"><span class="resistanceWarn-alert cursor-pointer radius"><p>'+val+'</p><button class="cursor-pointer radius" ng-click="removeResistanceWarn();">确定</button></span></div>')($scope));
	}
	$rootScope.removeResistanceWarn= function(){
		$(".resistanceWarn").remove();
		//万用表表针归位
		multimeterService.Mdata.multimeterblackRecover();
		multimeterService.Mdata.multimeterredRecover();
	}
	//弹出请先更新插件警告框
	$rootScope.createVersionGetWarn= function(val){
		if($(".resistanceWarn").length>0){
			return;
		}
		//$(".alert-container").html($compile('<div class="resistanceWarn z-index-100"><span class="resistanceWarn-alert radius"><p>'+val+'</p></span></div>')($scope));
	}
	$rootScope.removeVersionGetWarn= function(){
		$(".resistanceWarn").remove();	
	}
}])
