var mainModule=angular.module('MainModule',['multimeterModule','ui.router']);

mainModule.controller('MainCtrl',['$scope','$rootScope','PageService','multimeterService',function($scope,$rootScope,PageService,multimeterService){
	//获取页面中要使用的数据，比如路径等
	$scope.pageServicePdata=PageService.Pdata;
	//获取页面中使用的控制类参数，比如显示隐藏，比如状态码
	$scope.pageServicePctrl=PageService.Pctrl;
	//页面路径(初始值是概述的功能页面)
	$scope.templateNo='1';
	//点火开关打到什么档位，1代表lock档
	$scope.stalls=1;
	//点火开关打到什么档位，就执行什么档位的动画
	$scope.ignitionAnimateStalls=1;
	//万用表的显示隐藏
	$scope.multimeterServiceMdata = multimeterService.Mdata;
	//是否清除了故障
	$scope.clearMalfunctionStay=0;
	//仪表600到700之间的故障转速
	$scope.dashboardDeg=0;
	//显示隐藏的参数
	$scope.showOrHide={
		mainbody:false,//主页面的显示和隐藏
		frontCover:true,//封面的显示和隐藏
		front_cover_box1:false,//封面学习目标框的显示和隐藏
		front_cover_box2:false,//封面学习内容的显示和隐藏
		dashboardShow:false,//仪表板的显示和隐藏
		obdscanShow:false,//诊断仪的显示和隐藏
		menuPop:false,		//弹出框的显示和隐藏
		outlineFeatures:true,//概述的功能显示
		outlinePosition:false,//概述的位置
		outlineFeaturesBtn:false,//概述页面功能按钮悬浮框
		detectMeasureBox:false,//检查测量大外框
		detectBoxtTips:true,//检查页面可以点击出现测量部位的框
		detectNormalStatus:true,//检查页面正常状态‘
		detectMalfunctionStatus1:false,//检查页面故障一状态
		detectMalfunctionStatus2:false,//检查页面故障二状态
		detectMalfunctionStatus3:false,//检查页面故障三状态
		malfunctionBtn1:false,//检查页面初级线圈断路按钮显示和隐藏
		malfunctionBtn2:false//检查页面次级线圈断路按钮显示和隐藏

	}
	//头部导航切换方法
	$scope.chargeSrc=function(val){
		//切换页面,变更状态码
		$scope.templateNo=val;
		sysStay=val;
		if($scope.ignitionAnimateStalls==4){
			//初始化所有系统原理动画状态
			principleAnimateInitialize();
			if(sysStay==1){
				//概述页面点火动画,把策略页面的内容加进来
				animateClixk();
			}else if(sysStay==5){
				//策略页面点火动画
				animateClixk1();
			}
		}

	}
	//显示工具和隐藏
	$scope.toolShowOrClose=function(id,val){
		//如果不在功能页面则返回不允许点击
		if($scope.showOrHide.outlineFeatures==false&&sysStay==1){
			return;
		}
		if(id==1){
			if(val==1){
				//让诊断仪显示
				$scope.showOrHide.obdscanShow=true;
			}else if(val==0){
				//让诊断仪隐藏
				$scope.showOrHide.obdscanShow=false;
			}
		}else if(id==2){

		}
		else if(id==3){
			if(val==1){
				//让仪表显示
				$scope.showOrHide.dashboardShow=true;
				dragDiv();
			}else if(val==0){
				//让仪表隐藏
				$scope.showOrHide.dashboardShow=false;
			}
		}

	}
	//仪表点火开关
	$scope.ignition=function(){
		//lock档
		if($scope.stalls==1){
			$scope.stalls++;
			$scope.ignitionAnimateStalls=1;
			$(".dashboard_fire_lock2").css("transform","rotate(-72deg)");
			//==============================================
			$("#audio1")[0].pause();
			$("#audio2")[0].pause();
			$("#audio3")[0].pause();
			//初始化所有系统原理动画状态
			principleAnimateInitialize();
			//在lock acc时进行初始化
			lightInit();
			//==============================================
			//原理页面线路初始化
			principleLineInit();
			//==============================================
			//电路页面线路初始化
			circuitLineInit();
			//==============================================
			//诊断仪关闭页面
			$scope.obdscanPageGoto(0);
			//==============================================
			//万用表数据恢复，在lock，acc时
			$rootScope.recoverMultimeterData();
		}
		//acc档
		else if($scope.stalls==2){
			$scope.stalls++;
			$scope.ignitionAnimateStalls=2;
			$(".dashboard_fire_lock2").css("transform","rotate(-31deg)");
			//初始化所有系统原理动画状态
			principleAnimateInitialize();
			//在lock acc时进行初始化
			lightInit();
			//==============================================
			//原理页面线路初始化
			principleLineInit();
			//==============================================
			//电路页面线路初始化
			circuitLineInit();
			//==============================================
			//万用表数据恢复，在lock，acc时
			$rootScope.recoverMultimeterData();
		}
		//on档
		else if($scope.stalls==3){
			$scope.stalls++;
			$scope.ignitionAnimateStalls=3;
			$(".dashboard_fire_lock2").css("transform","rotate(23deg)");
			//故障状态下的仪表
			$scope.malfunction();
			//点火开关打到on档时车灯显示
			lightOn();
			//==============================================
			//原理页面打到on档时一条线亮
			principleLineOn();
			//==============================================
			//电路页面打到on档时右边的线变红
			circuitLineOn();
			//==============================================
			//万用表需要记录的测量点
			$rootScope.wybRecordProgress();
		}
		//start档
		else if($scope.stalls==4){
			$scope.stalls=1;
			$scope.ignitionAnimateStalls=4;
			$(".dashboard_fire_lock2").css("transform","rotate(60deg)");
			$("#audio1")[0].load();
			$("#audio1")[0].play();
			setTimeout(function(){
				$("#audio1")[0].pause();
				$("#audio2")[0].load();
				$("#audio2")[0].play();
				if(!$scope.showOrHide.detectNormalStatus||$scope.showOrHide.detectMalfunctionStatus3){
					$("#audio3")[0].load();
					$("#audio3")[0].play();
				}
				$(".dashboard_fire_lock2").css("transform","rotate(23deg)");
			},1000);
			//==============================================
			//点火开关打到start档时车灯显示
			lightStart();
			//故障状态下的仪表
			$scope.malfunction();
			//==============================================
			if(sysStay==1){
				//概述页面点火动画,把策略页面的内容加进来
				animateClixk();
			}else if(sysStay==5){
				//策略页面点火动画
				animateClixk1();
			}
			//==============================================
			//原理页面打到start档时一条线亮
			principleLineStart();
			//==============================================
			//电路页面打到start档1缸信号线变红，同时搭铁线变棕，之后同时变白。变白的同时高压电极闪一次火花。之后是3缸、4缸、2缸。
			circuitLinestart();
			//==============================================
			//策略页面点火动画
			//animateClixk1();
			//==============================================
			//万用表需要记录的测量点
			$rootScope.wybRecordProgress();
			//==============================================
			//要把是否清除故障码的按钮恢复过来
			$scope.clearMalfunctionStay=0;
			//在着车的情况下，如果是故障状态则要显示故障码
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan4.html'&&($scope.showOrHide.detectMalfunctionStatus1||$scope.showOrHide.detectMalfunctionStatus2||$scope.showOrHide.detectMalfunctionStatus3)){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan3.html';
			}
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'&&($scope.showOrHide.detectMalfunctionStatus1||$scope.showOrHide.detectMalfunctionStatus2||$scope.showOrHide.detectMalfunctionStatus3)){
				$("#malfunctionData").html("0.56")
			}
		}else{
			$scope.stalls=1;
		}
	}
	//故障状态下点火着车仪表指针，以及故障灯
	$scope.malfunction=function(){
		//故障状态下转速在600-700之间来回动，故障灯点亮
		if((!$scope.showOrHide.detectNormalStatus||$scope.showOrHide.detectMalfunctionStatus3)&&$scope.ignitionAnimateStalls==4){
			//故障灯点亮
			$(".dashboard_lamp_left4").show();
			//故障时点火有抖动声音
			$("#audio3")[0].load();
			$("#audio3")[0].play();
			//先关闭定时器
			clearInterval(dashboardTimer);
			dashboardTimer=setInterval(function(){
				if($scope.dashboardDeg==0){
					$(".dashboard_pointer1").css("transform","rotate(18deg)");
					$scope.dashboardDeg=1;
				}else{
					$(".dashboard_pointer1").css("transform","rotate(20deg)");
					$scope.dashboardDeg=0;
				}
			},100)
		}else{
			//关闭抖动声音
			$("#audio3")[0].pause();
			clearInterval(dashboardTimer);
			$(".dashboard_lamp_left4").hide();
		}
		//发动机转速和前氧传感器的数值变化
		$scope.engineSpeedDataChange();
	}
	//提示框的切换
	$scope.menuBox=function(val){
		if(val==1){
			//弹出框显示
			$scope.showOrHide.menuPop=true;
		}
		if(val==0){
			//弹出框消失
			$scope.showOrHide.menuPop=false;
		}
	}
	//功能和位置的切换,正常和故障的切换
	$scope.toggleInterface=function(id){
		if(id=='features'){
			$scope.showOrHide.outlineFeatures=true;
			$scope.showOrHide.outlinePosition=false;
		}
		if(id=='position'){
			$scope.showOrHide.outlinePosition=true;
			$scope.showOrHide.outlineFeatures=false;
		}
		if(id=='normal'){
			$scope.showOrHide.detectNormalStatus=true;
			$scope.showOrHide.detectMalfunctionStatus1=false;
			$scope.showOrHide.detectMalfunctionStatus2=false;
			//万用表需要记录的测量点
			$rootScope.wybRecordProgress();
			//故障状态下在数据流页面前氧传感器的值不一样
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'){
				$("#malfunctionData").html("0.36")
			}
			//正常状态转到故障状态的当前故障码页面需要改变
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan3.html'){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan4.html';
			}
			//故障状态下的仪表
			$scope.malfunction();

		}
		if(id=='malfunction1'){
			$scope.showOrHide.detectNormalStatus=false;
			$scope.showOrHide.detectMalfunctionStatus1=true;
			$scope.showOrHide.detectMalfunctionStatus2=false;
			//万用表需要记录的测量点
			$rootScope.wybRecordProgress();
			//故障状态下在数据流页面前氧传感器的值不一样
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'){
				$("#malfunctionData").html("0.56")
			}
			//正常状态转到故障状态的当前故障码页面需要改变
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan4.html'){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan3.html';
			}
			//故障状态下的仪表
			$scope.malfunction();

		}
		if(id=='malfunction2'){
			$scope.showOrHide.detectNormalStatus=false;
			$scope.showOrHide.detectMalfunctionStatus1=false;
			$scope.showOrHide.detectMalfunctionStatus2=true;
			//万用表需要记录的测量点
			$rootScope.wybRecordProgress();
			//故障状态下在数据流页面前氧传感器的值不一样
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'){
				$("#malfunctionData").html("0.56")
			}
			//正常状态转到故障状态的当前故障码页面需要改变
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan4.html'){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan3.html';
			}
			//故障状态下的仪表
			$scope.malfunction();
		}
	}
	//诊断仪的页面跳转
	$scope.obdscanPageGoto=function(val){
		if(val==0){
			//当值为0的时候跳到主页面
			$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscanMenu.html'
		}else{
			if($scope.ignitionAnimateStalls<3){
				return;
			}
			//此处关闭定时器会导致问题。
			//清除数据流数据的定时器
			//clearInterval(DataChangeTimer);
			//在故障状态下当前故障码显示应该要显示
			if(val==4){
				if($scope.showOrHide.detectMalfunctionStatus1||$scope.showOrHide.detectMalfunctionStatus2||$scope.showOrHide.detectMalfunctionStatus3){
					//在没有清除故障或者着车的情况下显示故障码，加一个点火线圈拔开的状态下也显示故障码
					if($scope.clearMalfunctionStay==0||$scope.ignitionAnimateStalls==4){
						val=3;
					}
				}
			}
			//故障清除页面只有在故障状态才可以进入
			if(val==5){
				//在点火线圈没有拔开的状态下，左侧选中的是正常按钮，点击清除故障就进不来这个页面
				if(!$scope.showOrHide.detectMalfunctionStatus3){
					if($scope.showOrHide.detectNormalStatus){
						return;
					}
				}
				//如果已经清除了故障码且不是着车状态就显示故障码已清除的页面
				if($scope.clearMalfunctionStay==1&&$scope.ignitionAnimateStalls!=4){
					val=6;
				}
			}
			//清除故障码以后，当前故障码页面是显示没有故障的
			if(val==6){
				$scope.clearMalfunctionStay=1;
			}

			//当值不为0的时候跳转到相应页面
			$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan'+val+'.html'

			/*因为dom的操作是在加载dom以后，所以要放到跳转以后执行*/
			if(val==2){
				//发动机转速和前氧传感器的数值变化
				$scope.engineSpeedDataChange();
			}
			//故障状态下在数据流页面前氧传感器的值不一样
			if(val=='2_1'){
				if($scope.showOrHide.detectMalfunctionStatus1||$scope.showOrHide.detectMalfunctionStatus2||$scope.showOrHide.detectMalfunctionStatus3){
					//加个定时器是因为还没有来得及加载完dom页面就执行了这句话
					/*setTimeout(function(){
						$("#malfunctionData").html("0.56");
					},100)*/
					//发动机转速和前氧传感器的数值变化
					$scope.engineSpeedDataChange();
				}
			}
		}

	}
	//数据流的上一页下一页跳转
	$scope.dataGotoPage=function(param){
		if(param=='next'){
			//下一页跳到2_1页面，数据流
			$scope.obdscanPageGoto('2_1');
		}
		if(param=='pre'){
			//上一页跳到2页面，数据流
			$scope.obdscanPageGoto('2');
		}
	}
	//检测页面热区点击
	$scope.dhxqOpen=function(val){
		if(val==1){
			//测量的图片出现
			$scope.showOrHide.detectMeasureBox=true;
			//测量可点击的热区消失
			$scope.showOrHide.detectBoxtTips=0;
			//关闭闪烁定时器
			clearInterval(detectTimer);
			$(".detect_dhxq1_cover").attr("src","images/detect_dhxq1_cover2.png");
			/*====================================================================*/
			//拔开的情况下存在故障三
			$scope.showOrHide.detectMalfunctionStatus3=true;
			//故障状态下在数据流页面前氧传感器的值不一样
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'){
				$("#malfunctionData").html("0.56")
			}
			//正常状态转到故障状态的当前故障码页面需要改变
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan4.html'){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan3.html';
			}
			//故障状态下的仪表
			$scope.malfunction();

		}else{
			//测量的图片消失
			$scope.showOrHide.detectMeasureBox=false;
			//测量可点击的热区出现
			$scope.showOrHide.detectBoxtTips=1;
			//打开闪烁
			tipBoxShark();
			$(".detect_dhxq1_cover").attr("src","images/detect_dhxq1_cover1.png");
			/*====================================================================*/
			//合上的情况下不存在故障三
			$scope.showOrHide.detectMalfunctionStatus3=false;
			//故障状态下在数据流页面前氧传感器的值不一样
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan2_1.html'&&$scope.showOrHide.detectNormalStatus){
				$("#malfunctionData").html("0.36")
			}
			//正常状态转到故障状态的当前故障码页面需要改变
			if($scope.pageServicePdata.obdscanSrc=='template/obdscan/obdscan3.html'&&$scope.showOrHide.detectNormalStatus){
				$scope.pageServicePdata.obdscanSrc='template/obdscan/obdscan4.html';
			}
			//故障状态下的仪表
			$scope.malfunction();
			/*====================================================================*/
			//万用表表针归位
			multimeterService.Mdata.multimeterblackRecover();
			multimeterService.Mdata.multimeterredRecover();
			//电阻档的情况下黑表笔没有在热区上那么万用表将恢复初值状态
			if((multimeterService.Mint.In1MultiLogic_x_Pass2Ohm_x_x=='1')){
				//数值
				multimeterService.Mout.Out1MultiLogic_x_ToScreen_x_x='1.';
				//单位
				multimeterService.Mdata.multimeterScreenUnit = " ";
			}
			//电压档的情况下黑表笔没有在热区上那么万用表将恢复初值状态
			if((multimeterService.Mint.In1MultiLogic_x_DCVlt_x_x=='1')){
				//数值
				multimeterService.Mout.Out1MultiLogic_x_ToScreen_x_x='0';
			}
		}

	}
	//发动机转速和前氧传感器的数值变化
	$scope.engineSpeedDataChange=function(){
		var dataChange=1;
		clearInterval(DataChangeTimer);
		DataChangeTimer=setInterval(function(){
			//正常状态下发动机转速
			if($scope.showOrHide.detectNormalStatus&&!$scope.showOrHide.detectMalfunctionStatus3){
				if($scope.ignitionAnimateStalls==4){
					if(dataChange==1){
						//发动机转速的数值变化
						$(".engine_speed_data").html("750");
						//前氧传感器的数值变化
						$("#malfunctionData").html("0.36");
						dataChange++;
					}
					else if(dataChange==2){
						$(".engine_speed_data").html("725");
						$("#malfunctionData").html("0.6");
						dataChange++;
					}
					else if(dataChange==3){
						$(".engine_speed_data").html("770");
						$("#malfunctionData").html("0.46");
						dataChange=1;
					}
				}
			}
			//故障状态下发动机转速和前氧传感器的数值
			if($scope.showOrHide.detectMalfunctionStatus1||$scope.showOrHide.detectMalfunctionStatus2||$scope.showOrHide.detectMalfunctionStatus3){
				if($scope.ignitionAnimateStalls==4){
					if(dataChange==1){
						//发动机转速的数值变化
						$(".engine_speed_data").html("650");
						$("#malfunctionData").html("0.56");
						dataChange++;
					}
					else if(dataChange==2){
						$(".engine_speed_data").html("550");
						$("#malfunctionData").html("0.78");
						dataChange++;
					}
					else if(dataChange==3){
						$(".engine_speed_data").html("680");
						$("#malfunctionData").html("0.82");
						dataChange=1;
					}
				}
			}

		},500)
	}
}
])






